export const Invoice = [
  {
    invoiceId: Math.random(),
    invoiceNumber: 1,
    customerName: "ABC Customer",
    customerEmail: "abccustomer@gmail.com",
    customerAddress: "abc street, abc city",
    totalItems: 3,
    totalAmount: 500,
    remainingAmount: 500,
    dueDate: "05/01/2023",
    paidDate: null,
    status: "unPaid",
    items: [
      {
        lineItemId: Math.random(),
        lineItemName: "Labour Charge",
        labourName: "Dhakshu",
        hours: 2,
        amountPerHour: 100,
        totalLineItemAmount: 200,
        notes: "Done more hard work",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Employee Fair",
        labourName: "Santhosh",
        hours: 1,
        amountPerHour: 200,
        totalLineItemAmount: 200,
        notes: "Need to more improve on focusing",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Reimbursement",
        labourName: "Vinoth",
        hours: 2,
        amountPerHour: 50,
        totalLineItemAmount: 100,
        notes: "Paid for employee who paid customes tax",
      },
    ],
  },
  {
    invoiceId: Math.random(),
    invoiceNumber: 2,
    customerName: "XYZ Customer",
    customerEmail: "xyzcustomer@gmail.com",
    customerAddress: "xyz street, xyz city",
    totalItems: 2,
    totalAmount: 700,
    remainingAmount: 700,
    dueDate: "04/01/2023",
    paidDate: null,
    status: "unPaid",
    items: [
      {
        lineItemId: Math.random(),
        lineItemName: "Labour Charge",
        labourName: "Girish",
        hours: 3,
        amountPerHour: 150,
        totalLineItemAmount: 450,
        notes: "Good Work",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Employee Fair",
        labourName: "Purushotham",
        hours: 5,
        amountPerHour: 50,
        totalLineItemAmount: 250,
        notes: "Need more improvement",
      },
    ],
  },
  {
    invoiceId: Math.random(),
    invoiceNumber: 3,
    customerName: "Nike Customer",
    customerEmail: "nikecustomer@gmail.com",
    customerAddress: "nike street, nike city",
    totalItems: 3,
    totalAmount: 600,
    remainingAmount: 600,
    dueDate: "29/12/2022",
    paidDate: null,
    status: "late",
    items: [
      {
        lineItemId: Math.random(),
        lineItemName: "Labour Charge",
        labourName: "Chitra",
        hours: 2,
        amountPerHour: 100,
        totalLineItemAmount: 200,
        notes: "Works Fine & Fair",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Employee Fair",
        labourName: "Logesh",
        hours: 2,
        amountPerHour: 150,
        totalLineItemAmount: 300,
        notes: "Good Working Skills",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Reimbursement",
        labourName: "Ashok",
        hours: 2,
        amountPerHour: 50,
        totalLineItemAmount: 100,
        notes: "Need to communicate well",
      },
    ],
  },
  {
    invoiceId: Math.random(),
    invoiceNumber: 4,
    customerName: "Freaker Customer",
    customerEmail: "freakercustomer@gmail.com",
    customerAddress: "freaker street, freaker city",
    totalItems: 2,
    totalAmount: 900,
    remainingAmount: null,
    dueDate: "28/12/2022",
    paidDate: "27/12/2022",
    status: "paid",
    items: [
      {
        lineItemId: Math.random(),
        lineItemName: "Labour Charge",
        labourName: "Ponni",
        hours: 4,
        amountPerHour: 100,
        totalLineItemAmount: 400,
        notes: "Takes more time",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Employee Fair",
        labourName: "",
        hours: 2,
        amountPerHour: 250,
        totalLineItemAmount: 500,
        notes: "Cost is little more",
      },
    ],
  },
  {
    invoiceId: Math.random(),
    invoiceNumber: 5,
    customerName: "Speed Customer",
    customerEmail: "speedcustomer@gmail.com",
    customerAddress: "speed street, speed city",
    totalItems: 4,
    totalAmount: 800,
    remainingAmount: null,
    dueDate: "26/12/2022",
    paidDate: "25/12/2022",
    status: "paid",
    items: [
      {
        lineItemId: Math.random(),
        lineItemName: "Labour Charge",
        labourName: "Sai",
        hours: 1,
        amountPerHour: 200,
        totalLineItemAmount: 200,
        notes: "Fine worker",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Employee Fair",
        labourName: "Thambi",
        hours: 4,
        amountPerHour: 50,
        totalLineItemAmount: 200,
        notes: "Need to more improve on focusing",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Reimbursement",
        labourName: "Richard",
        hours: 3,
        amountPerHour: 300,
        totalLineItemAmount: 300,
        notes: "Paid for employee who paid customes tax",
      },
      {
        lineItemId: Math.random(),
        lineItemName: "Reimbursement",
        labourName: "Vinoth",
        hours: 1,
        amountPerHour: 100,
        totalLineItemAmount: 100,
        notes: "Skills are good",
      },
    ],
  },
];

export const formatAmount = (value) => {
  return value.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, "$&,");
};
